services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: apollo
      POSTGRES_PASSWORD: pass
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - app-network
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
      image: confluentinc/cp-kafka
      container_name: kafka
      depends_on:
        - zookeeper
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ports:
        - "9092:9092"
      networks:
        - app-network



  discovery-service:
    build: ./discovery-service
    container_name: discovery-dock
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1"]
      interval: 10s
      retries: 4
    networks:
      - app-network
    depends_on:
      - postgres

  config-service:
    build: ./config-service
    container_name: config-dock
    ports:
      - '9999:9999'
    expose:
      - '9999'
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9999/actuator/health || exit 1"]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
    depends_on:
      discovery-service:
        condition: service_healthy
    networks:
      - app-network

  etudiant-service:
    build: ./etudiant-service
    container_name: etudiant-dock
    ports:
      - '8080:8080'
    expose:
      - '8080'
    healthcheck:
      test: ["CMD-SHELL", "sleep 5 && curl -f http://localhost:8080/actuator/health || exit 1"]
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
      - CONFIG_SERVICE_URL=http://config-dock:9999
    depends_on:
      config-service:
        condition: service_healthy
    networks:
      - app-network
  cours-service:
    build: ./cours-service
    container_name: cours-dock
    ports:
      - '8081:8081'
    expose:
      - '8081'
    healthcheck:
      test: ["CMD-SHELL", "sleep 5 && curl -f http://localhost:8081/actuator/health || exit 1"]
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
      - CONFIG_SERVICE_URL=http://config-dock:9999
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/gestion
      - SPRING_DATASOURCE_USERNAME=apollo
      - SPRING_DATASOURCE_PASSWORD=pass
    depends_on:
      config-service:
        condition: service_healthy
    networks:
      - app-network


  inscription-service:
    build: ./inscription-service
    container_name: inscription-dock
    ports:
      - '8084:8084'
    expose:
      - '8084'

    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
      - CONFIG_SERVICE_URL=http://config-dock:9999
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/gestion
      - SPRING_DATASOURCE_USERNAME=apollo
      - SPRING_DATASOURCE_PASSWORD=pass
    depends_on:
      etudiant-service:
        condition: service_healthy
      cours-service:
        condition: service_healthy
      config-service:
        condition: service_healthy
    networks:
      - app-network

  resultat-service:
    build: ./resultat-service
    container_name: resultat-dock
    ports:
      - '8082:8082'
    expose:
      - '8082'

    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
      - CONFIG_SERVICE_URL=http://config-dock:9999
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/gestion
      - SPRING_DATASOURCE_USERNAME=apollo
      - SPRING_DATASOURCE_PASSWORD=pass
    depends_on:
      etudiant-service:
        condition: service_healthy
      cours-service:
        condition: service_healthy
      config-service:
        condition: service_healthy
    networks:
      - app-network

  prof-service:
    build: ./prof-service
    container_name: prof-dock
    ports:
      - '8083:8083'
    expose:
      - '8083'

    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
      - CONFIG_SERVICE_URL=http://config-dock:9999
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/gestion
      - SPRING_DATASOURCE_USERNAME=apollo
      - SPRING_DATASOURCE_PASSWORD=pass
    depends_on:
      config-service:
        condition: service_healthy
    networks:
      - app-network


  notification-service:
    build: ./notification-service
    container_name: notification-dock
    ports:
      - '8099:8099'
    expose:
      - '8099'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
      - CONFIG_SERVICE_URL=http://config-dock:9999
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
      - CONFIG_SERVICE_URL=http://config-dock:9999
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/gestion
      - SPRING_DATASOURCE_USERNAME=apollo
      - SPRING_DATASOURCE_PASSWORD=pass
      - KAFKA_BROKER_URL=kafka:9092

    networks:
      - app-network

    depends_on:
      config-service:
        condition: service_healthy


  gateway-service:
    build: ./gateway-service
    container_name: gateway-dock
    ports:
      - '8888:8888'
    expose:
      - '8888'
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8888/actuator/health || exit 1"]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
      - CONFIG_SERVICE_URL=http://config-dock:9999
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/gestion
      - SPRING_DATASOURCE_USERNAME=apollo
      - SPRING_DATASOURCE_PASSWORD=pass
    depends_on:
      discovery-service:
        condition: service_healthy
    networks:
      - app-network



networks:
  app-network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
